"""
Decision Agent.

Responsible for selecting the most appropriate document type
and generating reasonable assumptions for missing information.
"""

from app.services.assumption_service import AssumptionService
from app.services.gemini_service import GeminiService
from app.services.prompt_builder import PromptBuilder
from app.tools.logger import logger


class DecisionAgent:
    """
    Autonomous Decision Agent.

    Responsibilities:
    - Determine the document type.
    - Generate assumptions for missing information.
    """

    def __init__(self) -> None:
        self.llm = GeminiService()

    def execute(
        self,
        request: str,
        execution_plan: list[str],
    ) -> tuple[str, list[str]]:
        """
        Determine document type and assumptions.

        Parameters
        ----------
        request : str
            User request.

        execution_plan : list[str]
            Execution plan generated by Planner Agent.

        Returns
        -------
        tuple[str, list[str]]
            (document_type, assumptions)
        """

        logger.info("Decision Agent Started.")

        prompt = PromptBuilder.build_decision_prompt(
            request=request,
            execution_plan=execution_plan,
        )

        response = self.llm.invoke(prompt)

        document_type = "Business Proposal"

        for line in response.splitlines():

            line = line.strip()

            if line.lower().startswith("document type"):

                document_type = line.split(":", 1)[1].strip()
                break

        assumptions = AssumptionService.generate_assumptions(
            document_type=document_type
        )

        logger.info(
            "Decision Agent Completed. Selected document type: %s",
            document_type,
        )

        return document_type, assumptions