"""
Reflection Agent.

Responsible for reviewing the generated document
before it is converted into a Word document.
"""

from app.services.gemini_service import GeminiService
from app.services.prompt_builder import PromptBuilder
from app.tools.logger import logger


class ReflectionAgent:
    """
    Autonomous Reflection Agent.

    Responsibilities:
    - Review generated content.
    - Check completeness.
    - Check professional quality.
    - Approve or reject the document.
    """

    def __init__(self) -> None:
        self.llm = GeminiService()

    def execute(
        self,
        generated_content: str,
    ) -> tuple[bool, str]:
        """
        Review the generated document.

        Parameters
        ----------
        generated_content : str
            Document generated by the Executor Agent.

        Returns
        -------
        tuple[bool, str]
            (is_approved, reflection_feedback)
        """

        logger.info("Reflection Agent Started.")

        prompt = PromptBuilder.build_reflection_prompt(
            document=generated_content
        )

        reflection_feedback = self.llm.invoke(prompt)

        first_line = (
            reflection_feedback.strip()
            .splitlines()[0]
            .strip()
            .upper()
        )

        is_approved = first_line == "APPROVED"

        logger.info(
            "Reflection Agent Completed. Approved: %s",
            is_approved,
        )

        return is_approved, reflection_feedback