"""
Document Service.

Coordinates the generation of Microsoft Word documents.
"""

from app.tools.docx_tool import DocumentGenerator
from app.utils.helpers import generate_output_filename


class DocumentService:
    """
    Handles document generation workflow.
    """

    @staticmethod
    def create_document(
        document_type: str,
        generated_content: str,
    ) -> str:
        """
        Generate and save the final Word document.

        Parameters
        ----------
        document_type : str
            Type of business document.

        generated_content : str
            Final content generated by the LLM.

        Returns
        -------
        str
            Path to the generated document.
        """

        filename = generate_output_filename(document_type)

        output_path = DocumentGenerator.generate_document(
            title=document_type,
            content=generated_content,
            output_filename=filename,
        )

        return output_path